name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make install
      
  debug:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Print debug info
      run: ./export_symbols.sh

  demo:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Run demo
      run: python3 demos/demo.py
